# Generated by Django 2.1.3 on 2019-03-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20190308_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='mix',
            name='pts',
            field=models.IntegerField(default=0, verbose_name='pts'),
        ),
    ]
