# Generated by Django 2.1.3 on 2019-03-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20190312_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='mix',
            field=models.FileField(default='', upload_to='mix/', verbose_name='混音音乐'),
        ),
    ]
