# Generated by Django 2.1.3 on 2019-03-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_mix_mix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mix',
            name='pts',
        ),
    ]
